ym: '202412'
run_id: 20251105T203543
cost: C:\Users\sgddsf\Desktop\minimum\ArcticRoute\data_processed\ice_forecast\merged\ice_cost_202412.nc
time_index: 2
start_ij:
- 200
- 150
goal_ij:
- 320
- 480
start_latlon: null
goal_latlon: null
no_diagonal: false
geojson: null
git: {}
env:
  python: 3.11.9
  executable: C:\Users\sgddsf\AppData\Local\Programs\Python\Python311\python.exe
  platform: Windows-10-10.0.26100-SP0
